#pragma once
// 引入 borealis 的 ControllerButton 和 BrlsKeyboardScancode 类型。
#include <borealis.hpp>

#include "core/enums.h"
// 引入 libretro 手柄按键 ID。
#include "third_party/mgba/src/platform/libretro/libretro.h"

namespace beiklive::input
{
// retro 键值索引映射
static const RetroNameMap k_retroNames[] = {
    { "retro_A",      RETRO_DEVICE_ID_JOYPAD_A      },
    { "retro_B",      RETRO_DEVICE_ID_JOYPAD_B      },
    { "retro_X",      RETRO_DEVICE_ID_JOYPAD_X      },
    { "retro_Y",      RETRO_DEVICE_ID_JOYPAD_Y      },
    { "retro_up",     RETRO_DEVICE_ID_JOYPAD_UP     },
    { "retro_down",   RETRO_DEVICE_ID_JOYPAD_DOWN   },
    { "retro_left",   RETRO_DEVICE_ID_JOYPAD_LEFT   },
    { "retro_right",  RETRO_DEVICE_ID_JOYPAD_RIGHT  },
    { "retro_l",      RETRO_DEVICE_ID_JOYPAD_L      },
    { "retro_r",      RETRO_DEVICE_ID_JOYPAD_R      },
    { "retro_l2",     RETRO_DEVICE_ID_JOYPAD_L2     },
    { "retro_r2",     RETRO_DEVICE_ID_JOYPAD_R2     },
    { "retro_l3",     RETRO_DEVICE_ID_JOYPAD_L3     },
    { "retro_r3",     RETRO_DEVICE_ID_JOYPAD_R3     },
    { "retro_start",  RETRO_DEVICE_ID_JOYPAD_START  },
    { "retro_select", RETRO_DEVICE_ID_JOYPAD_SELECT },
};

static const RetroNameMap k_brlsNames[] = {
    // 键盘值索引
    { "brls_key_space",         brls::BRLS_KBD_KEY_SPACE         },
    { "brls_key_apostrophe",    brls::BRLS_KBD_KEY_APOSTROPHE    },
    { "brls_key_comma",         brls::BRLS_KBD_KEY_COMMA         },
    { "brls_key_minus",         brls::BRLS_KBD_KEY_MINUS         },
    { "brls_key_period",        brls::BRLS_KBD_KEY_PERIOD        },
    { "brls_key_slash",         brls::BRLS_KBD_KEY_SLASH         },
    { "brls_key_0",             brls::BRLS_KBD_KEY_0             },
    { "brls_key_1",             brls::BRLS_KBD_KEY_1             },
    { "brls_key_2",             brls::BRLS_KBD_KEY_2             },
    { "brls_key_3",             brls::BRLS_KBD_KEY_3             },
    { "brls_key_4",             brls::BRLS_KBD_KEY_4             },
    { "brls_key_5",             brls::BRLS_KBD_KEY_5             },
    { "brls_key_6",             brls::BRLS_KBD_KEY_6             },
    { "brls_key_7",             brls::BRLS_KBD_KEY_7             },
    { "brls_key_8",             brls::BRLS_KBD_KEY_8             },
    { "brls_key_9",             brls::BRLS_KBD_KEY_9             },
    { "brls_key_semicolon",     brls::BRLS_KBD_KEY_SEMICOLON     },
    { "brls_key_equal",         brls::BRLS_KBD_KEY_EQUAL         },
    { "brls_key_a",             brls::BRLS_KBD_KEY_A             },
    { "brls_key_b",             brls::BRLS_KBD_KEY_B             },
    { "brls_key_c",             brls::BRLS_KBD_KEY_C             },
    { "brls_key_d",             brls::BRLS_KBD_KEY_D             },
    { "brls_key_e",             brls::BRLS_KBD_KEY_E             },
    { "brls_key_f",             brls::BRLS_KBD_KEY_F             },
    { "brls_key_g",             brls::BRLS_KBD_KEY_G             },
    { "brls_key_h",             brls::BRLS_KBD_KEY_H             },
    { "brls_key_i",             brls::BRLS_KBD_KEY_I             },
    { "brls_key_j",             brls::BRLS_KBD_KEY_J             },
    { "brls_key_k",             brls::BRLS_KBD_KEY_K             },
    { "brls_key_l",             brls::BRLS_KBD_KEY_L             },
    { "brls_key_m",             brls::BRLS_KBD_KEY_M             },
    { "brls_key_n",             brls::BRLS_KBD_KEY_N             },
    { "brls_key_o",             brls::BRLS_KBD_KEY_O             },
    { "brls_key_p",             brls::BRLS_KBD_KEY_P             },
    { "brls_key_q",             brls::BRLS_KBD_KEY_Q             },
    { "brls_key_r",             brls::BRLS_KBD_KEY_R             },
    { "brls_key_s",             brls::BRLS_KBD_KEY_S             },
    { "brls_key_t",             brls::BRLS_KBD_KEY_T             },
    { "brls_key_u",             brls::BRLS_KBD_KEY_U             },
    { "brls_key_v",             brls::BRLS_KBD_KEY_V             },
    { "brls_key_w",             brls::BRLS_KBD_KEY_W             },
    { "brls_key_x",             brls::BRLS_KBD_KEY_X             },
    { "brls_key_y",             brls::BRLS_KBD_KEY_Y             },
    { "brls_key_z",             brls::BRLS_KBD_KEY_Z             },
    { "brls_key_left_bracket",  brls::BRLS_KBD_KEY_LEFT_BRACKET  },
    { "brls_key_backslash",     brls::BRLS_KBD_KEY_BACKSLASH     },
    { "brls_key_right_bracket", brls::BRLS_KBD_KEY_RIGHT_BRACKET },
    { "brls_key_grave_accent",  brls::BRLS_KBD_KEY_GRAVE_ACCENT  },
    { "brls_key_world_1",       brls::BRLS_KBD_KEY_WORLD_1       },
    { "brls_key_world_2",       brls::BRLS_KBD_KEY_WORLD_2       },
    { "brls_key_escape",        brls::BRLS_KBD_KEY_ESCAPE        },
    { "brls_key_enter",         brls::BRLS_KBD_KEY_ENTER         },
    { "brls_key_tab",           brls::BRLS_KBD_KEY_TAB           },
    { "brls_key_backspace",     brls::BRLS_KBD_KEY_BACKSPACE     },
    { "brls_key_insert",        brls::BRLS_KBD_KEY_INSERT        },
    { "brls_key_delete",        brls::BRLS_KBD_KEY_DELETE        },
    { "brls_key_right",         brls::BRLS_KBD_KEY_RIGHT         },
    { "brls_key_left",          brls::BRLS_KBD_KEY_LEFT          },
    { "brls_key_down",          brls::BRLS_KBD_KEY_DOWN          },
    { "brls_key_up",            brls::BRLS_KBD_KEY_UP            },
    { "brls_key_page_up",       brls::BRLS_KBD_KEY_PAGE_UP       },
    { "brls_key_page_down",     brls::BRLS_KBD_KEY_PAGE_DOWN     },
    { "brls_key_home",          brls::BRLS_KBD_KEY_HOME          },
    { "brls_key_end",           brls::BRLS_KBD_KEY_END           },
    { "brls_key_caps_lock",     brls::BRLS_KBD_KEY_CAPS_LOCK     },
    { "brls_key_scroll_lock",   brls::BRLS_KBD_KEY_SCROLL_LOCK   },
    { "brls_key_num_lock",      brls::BRLS_KBD_KEY_NUM_LOCK      },
    { "brls_key_print_screen",  brls::BRLS_KBD_KEY_PRINT_SCREEN  },
    { "brls_key_pause",         brls::BRLS_KBD_KEY_PAUSE         },
    { "brls_key_f1",            brls::BRLS_KBD_KEY_F1            },
    { "brls_key_f2",            brls::BRLS_KBD_KEY_F2            },
    { "brls_key_f3",            brls::BRLS_KBD_KEY_F3            },
    { "brls_key_f4",            brls::BRLS_KBD_KEY_F4            },
    { "brls_key_f5",            brls::BRLS_KBD_KEY_F5            },
    { "brls_key_f6",            brls::BRLS_KBD_KEY_F6            },
    { "brls_key_f7",            brls::BRLS_KBD_KEY_F7            },
    { "brls_key_f8",            brls::BRLS_KBD_KEY_F8            },
    { "brls_key_f9",            brls::BRLS_KBD_KEY_F9            },
    { "brls_key_f10",           brls::BRLS_KBD_KEY_F10           },
    { "brls_key_f11",           brls::BRLS_KBD_KEY_F11           },
    { "brls_key_f12",           brls::BRLS_KBD_KEY_F12           },
    { "brls_key_f13",           brls::BRLS_KBD_KEY_F13           },
    { "brls_key_f14",           brls::BRLS_KBD_KEY_F14           },
    { "brls_key_f15",           brls::BRLS_KBD_KEY_F15           },
    { "brls_key_f16",           brls::BRLS_KBD_KEY_F16           },
    { "brls_key_f17",           brls::BRLS_KBD_KEY_F17           },
    { "brls_key_f18",           brls::BRLS_KBD_KEY_F18           },
    { "brls_key_f19",           brls::BRLS_KBD_KEY_F19           },
    { "brls_key_f20",           brls::BRLS_KBD_KEY_F20           },
    { "brls_key_f21",           brls::BRLS_KBD_KEY_F21           },
    { "brls_key_f22",           brls::BRLS_KBD_KEY_F22           },
    { "brls_key_f23",           brls::BRLS_KBD_KEY_F23           },
    { "brls_key_f24",           brls::BRLS_KBD_KEY_F24           },
    { "brls_key_f25",           brls::BRLS_KBD_KEY_F25           },
    { "brls_key_kp_0",          brls::BRLS_KBD_KEY_KP_0          },
    { "brls_key_kp_1",          brls::BRLS_KBD_KEY_KP_1          },
    { "brls_key_kp_2",          brls::BRLS_KBD_KEY_KP_2          },
    { "brls_key_kp_3",          brls::BRLS_KBD_KEY_KP_3          },
    { "brls_key_kp_4",          brls::BRLS_KBD_KEY_KP_4          },
    { "brls_key_kp_5",          brls::BRLS_KBD_KEY_KP_5          },
    { "brls_key_kp_6",          brls::BRLS_KBD_KEY_KP_6          },
    { "brls_key_kp_7",          brls::BRLS_KBD_KEY_KP_7          },
    { "brls_key_kp_8",          brls::BRLS_KBD_KEY_KP_8          },
    { "brls_key_kp_9",          brls::BRLS_KBD_KEY_KP_9          },
    { "brls_key_kp_decimal",    brls::BRLS_KBD_KEY_KP_DECIMAL    },
    { "brls_key_kp_divide",     brls::BRLS_KBD_KEY_KP_DIVIDE     },
    { "brls_key_kp_multiply",   brls::BRLS_KBD_KEY_KP_MULTIPLY   },
    { "brls_key_kp_subtract",   brls::BRLS_KBD_KEY_KP_SUBTRACT   },
    { "brls_key_kp_add",        brls::BRLS_KBD_KEY_KP_ADD        },
    { "brls_key_kp_enter",      brls::BRLS_KBD_KEY_KP_ENTER      },
    { "brls_key_kp_equal",      brls::BRLS_KBD_KEY_KP_EQUAL      },
    { "brls_key_left_shift",    brls::BRLS_KBD_KEY_LEFT_SHIFT    },
    { "brls_key_left_control",  brls::BRLS_KBD_KEY_LEFT_CONTROL  },
    { "brls_key_left_alt",      brls::BRLS_KBD_KEY_LEFT_ALT      },
    { "brls_key_left_super",    brls::BRLS_KBD_KEY_LEFT_SUPER    },
    { "brls_key_right_shift",   brls::BRLS_KBD_KEY_RIGHT_SHIFT   },
    { "brls_key_right_control", brls::BRLS_KBD_KEY_RIGHT_CONTROL },
    { "brls_key_right_alt",     brls::BRLS_KBD_KEY_RIGHT_ALT     },
    { "brls_key_right_super",   brls::BRLS_KBD_KEY_RIGHT_SUPER   },
    { "brls_key_menu",          brls::BRLS_KBD_KEY_MENU          },

    // 手柄值索引
    { "brls_button_lt",    brls::BUTTON_LT    },
    { "brls_button_lb",    brls::BUTTON_LB    },
    { "brls_button_lsb",   brls::BUTTON_LSB   },
    { "brls_button_up",    brls::BUTTON_UP    },
    { "brls_button_right", brls::BUTTON_RIGHT },
    { "brls_button_down",  brls::BUTTON_DOWN  },
    { "brls_button_left",  brls::BUTTON_LEFT  },
    { "brls_button_back",  brls::BUTTON_BACK  },
    { "brls_button_guide", brls::BUTTON_GUIDE },
    { "brls_button_start", brls::BUTTON_START },
    { "brls_button_rsb",   brls::BUTTON_RSB   },
    { "brls_button_y",     brls::BUTTON_Y     },
    { "brls_button_b",     brls::BUTTON_B     },
    { "brls_button_a",     brls::BUTTON_A     },
    { "brls_button_x",     brls::BUTTON_X     },
    { "brls_button_rb",    brls::BUTTON_RB    },
    { "brls_button_rt",    brls::BUTTON_RT    },
    //     LEFT_X,
    // LEFT_Y,

    // RIGHT_X, // also called 5th axis
    // RIGHT_Y, // also called 4th axis

    // LEFT_Z, // LT
    // RIGHT_Z, // RT
};


// 根据 code 获取对应的 borealis 键名（如果存在）
std::string parseBrlsButton(const int code);


} // namespace beiklive

