#pragma once

#include "stub_ui/UiPrimitives.hpp"

namespace beiklive::nds_stub::ui {

using namespace beiklive::stub_ui;

} // namespace beiklive::nds_stub::ui

#define NDS_STUB_KEYICON_A STUB_UI_KEYICON_A
#define NDS_STUB_KEYICON_B STUB_UI_KEYICON_B
#define NDS_STUB_KEYICON_X STUB_UI_KEYICON_X
#define NDS_STUB_KEYICON_Y STUB_UI_KEYICON_Y
#define NDS_STUB_KEYICON_LSB STUB_UI_KEYICON_LSB
#define NDS_STUB_KEYICON_RSB STUB_UI_KEYICON_RSB
#define NDS_STUB_KEYICON_LT STUB_UI_KEYICON_LT
#define NDS_STUB_KEYICON_RT STUB_UI_KEYICON_RT
#define NDS_STUB_KEYICON_LB STUB_UI_KEYICON_LB
#define NDS_STUB_KEYICON_RB STUB_UI_KEYICON_RB
#define NDS_STUB_KEYICON_START STUB_UI_KEYICON_START
#define NDS_STUB_KEYICON_BACK STUB_UI_KEYICON_BACK
#define NDS_STUB_KEYICON_LEFT STUB_UI_KEYICON_LEFT
#define NDS_STUB_KEYICON_UP STUB_UI_KEYICON_UP
#define NDS_STUB_KEYICON_RIGHT STUB_UI_KEYICON_RIGHT
#define NDS_STUB_KEYICON_DOWN STUB_UI_KEYICON_DOWN
#define NDS_STUB_KEYICON_UNKNOWN STUB_UI_KEYICON_UNKNOWN
