name: Build Switch NRO

on:
  push:
    tags:
      - 'v*'
      - 'V*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装额外依赖
        run: |
          dkp-pacman -S --noconfirm --needed switch-dev

      - name: 编译 NRO
        run: |
          chmod +x switchbuild.sh
          ./switchbuild.sh

      - name: 上传 NRO 到 Release
        uses: softprops/action-gh-release@v2
        with:
          files: build_switch/GBAStation.nro
